name: Python
on: [push]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v2
      id: cache-id
      with:
        path: ./checkpoints/  # what we cache: the virtualenv
        # The cache key depends on requirements.txt
        key: ${{ runner.os }}-checkpoints-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-checkpoints-8d23008a57ddd4f578262b5f0592bd4a9d30d8c92418f0b486635b6969876a15
    - if: steps.cache-checkpoints.outputs.cache-hit != 'true'
      run: |
         ls
    - run: |
       ls checkpoints
