name: Python
on: [push]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v2
      id: cache-id
      with:
        path: ${{ runner.temp }}/checkpoints
        key: ${{ runner.os }}-cache-hello-world-key-v1.0
    # Required action
    - uses: airvzxf/cache-anything-new-action@v1.0.1
      with:
        script: 'install.sh'
        is_cached: ${{ steps.cache-id.outputs.cache-hit }}
        cache: ${{ runner.temp }}/checkpoints
    - run: |
       # ./checkpoints/bin/pip install torch==1.12.0+cpu torchvision==0.13.0+cpu torchaudio==0.12.0 --extra-index-url https://download.pytorch.org/whl/cpu
       echo "a" >> checkpoints/HERE
       ls checkpoints/bin
